### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by sidan5** [iosdevzone/IDZPrecompiledFLAC#1]
When would it be compiled to arm64?

**Comment by iosdevzone** [comment]
Hi there,

I don't have access to a arm64 bit device just yet and I would not like to publish an untested version. If you check out the tutorials on my site (www.iosdeveloperzone.com) where I explain the scripts used to build the libraries you should be able to add arm64!

If I get a chance I will update the scripts myself, but it could be a few days.

Hope this helps,
idz

**Comment by iosdevzone** [comment]
Now supports arm64.
