### ISSUE TITLE
problem in arm64

### ISSUE THREAD

**Issue by onuryilm** [iosdevzone/IDZPrecompiledFLAC#2]
just tested in arm64 and i can say that its not working for arm64 however it works fine for all previous architectures.

**Comment by iosdevzone** [comment]
This was a first, untested, unreleased attempt. When you say "it does not work" could you provide more information? What did you try? How did you determine it was not working? More details will help me work out what is going wrong!

**Comment by onuryilm** [comment]
I try to build in xcode, when i build for standard achitectures excluding arm64 there are no errors working fine.

but when i build for standard architectures (including 64-bit) i receive the errors saying

ld: warning: ignoring file /Users/onuryilmaz/Desktop/Google Drive/PROJELER/WRITE/app/write/Ogg.framework/Ogg, missing required architecture arm64 in file /Users/onuryilmaz/Desktop/Google Drive/PROJELER/WRITE/app/write/Ogg.framework/Ogg (2 slices)
ld: warning: ignoring file /Users/onuryilmaz/Desktop/Google Drive/PROJELER/WRITE/app/write/FLAC.framework/FLAC, missing required architecture arm64 in file /Users/onuryilmaz/Desktop/Google Drive/PROJELER/WRITE/app/write/FLAC.framework/FLAC (3 slices)
Undefined symbols for architecture arm64:

**Comment by iosdevzone** [comment]
Hi,

These errors indicate that your versions of Ogg.framework and FLAC.framework have somehow been modified from the ones in IDZPrecompiledOgg and IDZPrecompiledFLAC, specifically some architecture slices have been removed or corrupted. The latest version of the libraries have 5 slices: armv7, armv7s, arm64, i386 and x86_64, whereas the ones you are using have 2 slices and 3 slices respectively.

Please refresh your versions and try again.

Assuming you put the files in the same location, you can check that all architectures are present using 

`lipo -info "/Users/onuryilmaz/Desktop/Google Drive/PROJELER/WRITE/app/write/Ogg.framework/Ogg"`

and

`lipo -info "/Users/onuryilmaz/Desktop/Google Drive/PROJELER/WRITE/app/write/FLAC.framework/FLAC"`

You should see that each has five slices, for example:

`Architectures in the fat file: FLAC are: i386 x86_64 armv7 (cputype (12) cpusubtype (11)) (cputype (16777228) cpusubtype (0))`

Regards,
idz

**Comment by onuryilm** [comment]
Hi,

Just found out that i have some problems with the paths. Your libraries works like a charm for arm64.

thanx&regards

**Comment by iosdevzone** [comment]
Glad we could figure out what was going on. Good Luck!
